language: python
python:
    - "3.6"

install:
    pip install -r requirements.txt

script:
    - pytest -s --cov=nba_scraper test_unit.py

env:
    - CODECOV_TOKEN='dafe83cc-3a71-4fc1-98bc-6b9d7f0b0d2f'

after_success:
    - codecov